version: '3.0'
services:

  react-in-docker:
    container_name: react-in-docker
    build:
      context: .
      dockerfile: ./react-in-docker/Dockerfile
    volumes:
      - ./react-in-docker/app/:/home/node/app
    ports:
      - ${PORT_DEV}:${PORT_DEV}
    environment:
      - NODE_ENV=development
      - PORT=${PORT_DEV}
    networks:
     - frontend
    command: npm run serve

networks:
    frontend:
